

import type { Metadata } from "next";
import Dashboard from "./components/dashboard";
import "../globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
       <div className="grid grid-cols-4 p-6">
        <Dashboard /> 
        {children}
      </div>

  );
}
